server:
  port: 8080
spring:
  profiles:
    active: "default"
  datasource:
    url: jdbc:postgresql://localhost:5432/scrum
    username: carddealer
    password: fullH0uz3
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    generate-ddl: true

